name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: src/SimpleProxy
      run: docker build . --file Dockerfile --tag tiagosoczek\simple-proxy:$(date +%s) --tag tiagosoczek\latest

    - uses: actions/docker/login@master
    - name: Push image
      run: docker push tiagosoczek\simple-proxy:$(date +%s) tiagosoczek\simple-proxy:latest
